name: build
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  push:
    branches:
    - main
jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
        - wallaby
        - xena
        - yoga
    steps:
    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v2
    - name: Configure Buildkit
      uses: docker/setup-buildx-action@v2
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup environment variables
      run: echo PROJECT_REF=$(cat manifest.yml | yq ".${{ matrix.release }}.sha") >> $GITHUB_ENV
    - name: Authenticate with Quay.io
      uses: docker/login-action@v2
      if: ${{ github.event_name == 'push' }}
      with:
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
    - name: Build image
      uses: docker/build-push-action@v3
      with:
        build-args: |-
          RELEASE=${{ matrix.release }}
          PROJECT=ironic
          PROJECT_REF=${{ env.PROJECT_REF }}
          EXTRAS=
          PROFILES=ipxe ipmi qemu tftp
          DIST_PACKAGES=ethtool lshw iproute2
          PIP_PACKAGES=python-dracclient sushy
        cache-from: type=gha,scope=${{ matrix.release }}
        cache-to: type=gha,mode=max,scope=${{ matrix.release }}
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name == 'push' }}
        tags: quay.io/vexxhost/ironic:${{ env.PROJECT_REF }}
    - name: Promote image
      uses: akhilerm/tag-push-action@v2.0.0
      if: github.ref == 'refs/heads/main'
      with:
        dst: quay.io/vexxhost/ironic:${{ matrix.release }}
        src: quay.io/vexxhost/ironic:${{ env.PROJECT_REF }}
